const SITE_IMAGES = [
  {
    key: 'home.hero.main',
    label: 'Inicio - imagen principal',
    section: 'Inicio',
    defaultUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
    alt: 'Gestion en salud',
    ratio: 'vertical',
  },
  {
    key: 'home.hero.secondary',
    label: 'Inicio - profesional de salud',
    section: 'Inicio',
    defaultUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80',
    alt: 'Profesional de salud',
    ratio: 'horizontal',
  },
  {
    key: 'home.hero.training',
    label: 'Inicio - capacitacion medica',
    section: 'Inicio',
    defaultUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80',
    alt: 'Capacitacion medica',
    ratio: 'horizontal',
  },
  {
    key: 'nosotros.intro.team',
    label: 'Nosotros - equipo',
    section: 'Nosotros',
    defaultUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=700&q=80',
    alt: 'Equipo Kadima Salud',
    ratio: '4:3',
  },
  {
    key: 'surge.intro.documents',
    label: 'SURGE - expedientes',
    section: 'SURGE',
    defaultUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80',
    alt: 'Gestion de expedientes SURGE',
    ratio: '4:3',
  },
  {
    key: 'equipos.intro.medical',
    label: 'Equipos - equipo medico',
    section: 'Equipos',
    defaultUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&q=80',
    alt: 'Equipo medico quirurgico',
    ratio: '4:3',
  },
  {
    key: 'services.auditoria-liquidacion.main',
    label: 'Auditoría de Liquidación - imagen principal',
    section: 'Servicios',
    defaultUrl: '/service-auditoria.svg',
    alt: 'Profesionales revisando documentación financiera y médica',
    ratio: '4:3',
  },
  {
    key: 'services.internacion-domiciliaria.main',
    label: 'Internación Domiciliaria - imagen principal',
    section: 'Servicios',
    defaultUrl: '/service-internacion.svg',
    alt: 'Profesional brindando atención médica personalizada',
    ratio: '4:3',
  },
  {
    key: 'services.control-diabetes.main',
    label: 'Control de Pacientes Diabéticos - imagen principal',
    section: 'Servicios',
    defaultUrl: '/service-diabetes.svg',
    alt: 'Seguimiento clínico y tecnología aplicada a la salud',
    ratio: '4:3',
  },
  {
    key: 'services.asesoramiento-prejudicial.main',
    label: 'Asesoramiento Pre-Judicial - imagen principal',
    section: 'Servicios',
    defaultUrl: '/service-prejudicial.svg',
    alt: 'Asesoramiento jurídico y sanitario preventivo',
    ratio: '4:3',
  },
]

const SITE_IMAGE_KEYS = new Set(SITE_IMAGES.map(image => image.key))

module.exports = { SITE_IMAGES, SITE_IMAGE_KEYS }
